version: 2
jobs:
  prodaction:
    branch: master
    tag: /v[0-9]+(\.[0-9]+)*/
    docker:
      - image: google/cloud-sdk:latest
    environment:
        ENV: PROD
    steps:
      - checkout
      - setup_remote_docker
      - run:
            name: deploy api
            command: |
                echo "===========Deploy As prodaction enviroment==========="
                echo $ACCT_AUTH | base64 -d > ${HOME}/gcloud-service-key.json
                gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
                gcloud config set project $PROJECT_ID
                chmod 500 bin/kms.sh
                chmod 500 bin/push_image.sh
                chmod 500 bin/deploy.sh
                bin/kms.sh d && \
                bin/push_image.sh && \
                bin/deploy.sh
  staging:
    branch: master
    docker:
      - image: google/cloud-sdk:latest
    environment:
        ENV: STD
    steps:
      - checkout
      - setup_remote_docker
      - run:
            name: deploy api
            command: |
                echo "===========Deploy As staging enviroment==========="
                echo $ACCT_AUTH | base64 -d > ${HOME}/gcloud-service-key.json
                gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
                gcloud config set project $PROJECT_ID
                chmod 500 bin/kms.sh
                chmod 500 bin/push_image.sh
                chmod 500 bin/deploy.sh
                bin/kms.sh d && \
                bin/push_image.sh && \
                bin/deploy.sh
  development:
    branch: develop
    docker:
      - image: google/cloud-sdk:latest
    environment:
        ENV: DEV
    steps:
      - checkout
      - setup_remote_docker
      - run:
            name: deploy api
            command: |
                echo "===========Deploy As development enviroment==========="
                echo $ACCT_AUTH | base64 -d > ${HOME}/gcloud-service-key.json
                gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
                gcloud config set project $PROJECT_ID
                chmod 500 bin/kms.sh
                chmod 500 bin/push_image.sh
                chmod 500 bin/deploy.sh
                bin/kms.sh d && \
                bin/push_image.sh && \
                bin/deploy.sh

workflows:
  version: 2
  my-workflow:
    jobs:
      - prodaction:
          context: GCP
      - staging:
          context: GCP
      - development:
          context: GCP