version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
            name: deploy api
            command: |
                echo $ACCT_AUTH | base64 -d > ${HOME}/gcloud-service-key.json
                cat  ${HOME}/gcloud-service-key.json
                gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
                echo $PROJECT_ID
                gcloud config set project $PROJECT_ID
                chmod 500 bin/kms.sh
                chmod 500 bin/psuh_image.sh
                chmod 500 bin/deploy.sh
                bin/kms.sh d
                bin/push_image.sh
                bin/deploy.sh

workflows:
  version: 2
  my-workflow:
    jobs:
      - build:
          context: GCP